---
- hosts: etcd_cluster
  tasks:
    - name: Update and install etcd
      apt:
        name: etcd
        state: present
        update_cache: yes

    - name: Kill all running etcd instances
      command: killall -q etcd
      register: result
      failed_when: "result.rc not in [0, 1]"

    - name: Start etcd
      script:
        cmd: "{{ playbook_dir }}/etcd/etcd.infra{{ ansible_host[-1:] }}.sh"