---
- hosts: monitoring
  pre_tasks:
    - name: Update and install prometheus
      apt:
        name: prometheus
        state: latest
        update_cache: yes

    # - name: Install and start node exporter
    #   script: "{{ playbook_dir }}/monitoring/node_exporter.sh"

    - name: Copy prometheus configuration file
      template:
        src: "{{ playbook_dir }}/monitoring/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        # mode: 0755
        owner: prometheus
        group: prometheus

    - name: Start prometheus
      service:
        name: prometheus
        state: started

    # - name: 
    #   file:
    #     path: "/etc/grafana/provisioning/dashboards/dashboards.yml"
    #     state: absent

  roles:
    - ansible-grafana-install
    - role: ansible-grafana-config
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
    
  tasks:
    - name: Create Grafana dashboard proviver
      copy:
        src: "{{ playbook_dir }}/monitoring/dashboards.yml"
        dest: "/etc/grafana/provisioning/dashboards/dashboards.yml"
        
    - name: Create Grafana dashboards dir
      file:
        path: /var/lib/grafana/dashboards
        state: directory

    - name: Copy dashboard config for nginx
      copy:
        src: "{{ playbook_dir }}/monitoring/nginx_dashboard.json"
        dest: "/var/lib/grafana/dashboards/nginx_dashboard.json"

    - name: Copy dashboard config for etcd
      copy:
        src: "{{ playbook_dir }}/monitoring/etcd_dashboard.json"
        dest: "/var/lib/grafana/dashboards/etcd_dashboard.json"

    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
      ignore_errors: true

    - name: Start node_exporter
      service:
        name: prometheus-node-exporter
        state: started
      ignore_errors: true