---
- hosts: web
  tasks:
    - name: Update and install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy config files, cert and index.html
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "{{ playbook_dir }}/web/nginx_static.conf", dest: "/etc/nginx/sites-available/static.conf"}
        - {src: "{{ playbook_dir }}/web/ssl-params.conf", dest: "/etc/nginx/ssl-params.conf"}
        - {src: "{{ playbook_dir }}/web/index.html", dest: "/var/www/html/"}
        - {src: "{{ playbook_dir }}/web/nginx-selfsigned.crt", dest: "/etc/ssl/certs/nginx-selfsigned.crt"}
        - {src: "{{ playbook_dir }}/web/nginx-selfsigned.key", dest: "/etc/ssl/private/nginx-selfsigned.key"}
        - {src: "{{ playbook_dir }}/web/dhparam.pem", dest: "/etc/nginx/dhparam.pem"}
      become: true

    - name: Create config symlink
      file:
        src: /etc/nginx/sites-available/static.conf
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        