version: '3.5'

networks:
  backend_net:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/24

services:
  web:
    image: mydebian-ssh
    env_file: .docker.env
    ports:
      - 80
      - 443
      - 8080
    networks:
      backend_net:
        ipv4_address: 172.77.0.2
  monitoring:
    image: mydebian-ssh
    env_file: .docker.env
    ports:
      - 80
      - 3000
      - 9090
    # Override ulimits pro monitoring
    # Vychozi stav se propisuje z host systemu, grafana vyzaduje vice
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      backend_net:
        ipv4_address: 172.77.0.3
  nginx-exporter:
    depends_on:
      - web
      - monitoring
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
      - 9113
    # Retries na 9999 je tempfix aby neexitnnul container nez se nastavi nginx
    command: "-nginx.scrape-uri=http://172.77.0.2:8080/stub_status -nginx.retries 9999"
    networks:
      backend_net:
        ipv4_address: 172.77.0.4
  etcd-00:
    image: mydebian-ssh
    ports:
      - 2379
    networks:
      backend_net:
        ipv4_address: 172.77.0.10
  etcd-01:
    image: mydebian-ssh
    ports:
      - 2379
    networks:
      backend_net:
        ipv4_address: 172.77.0.11
  etcd-02:
    image: mydebian-ssh
    ports:
      - 2379
    networks:
      backend_net:
        ipv4_address: 172.77.0.12
